# Generated by Django 4.0.5 on 2022-07-09 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(choices=[('Groceries & Stores', 'Groceries & Stores'), ('Fashion & Beauty', 'Fashion & Beauty'), ('Pets', 'Pets'), ('Drugstore & Personal Care', 'Drugstore & Personal Care'), ('Home & DIY', 'Home & DIY'), ('Devices & Electronics', 'Devices & Electronics'), ('Music, Video & Gaming', 'Music, Video & Gaming'), ('Books & Reading', 'Books & Reading'), ('Toys, Kids & Baby', 'Toys, Kids & Baby'), ('Automotive', 'Automotive'), ('Office & Professional', 'Office & Professional'), ('Sports & Fanshop', 'Sports & Fanshop'), ('Outdoors & Travels', 'Outdoors & Travels'), ('Other', 'Other')], max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.category'),
        ),
    ]
