# Generated by Django 4.0.5 on 2022-07-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_bids_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bids_image',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
